version: '3.8'

services:
  api-gateway:
    build:
      context: .
      dockerfile: apps/api-gateway/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - AUTH_SERVICE_HOST=auth-microservice
      - AUTH_SERVICE_PORT=3001
    depends_on:
      - auth-microservice
    networks:
      - microservices-network

  auth-microservice:
    build:
      context: .
      dockerfile: apps/auth-microservice/Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/auth
    depends_on:
      - mongodb
    networks:
      - microservices-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - microservices-network

volumes:
  mongodb_data:

networks:
  microservices-network:
    driver: bridge 